export interface BlogPost {
  slug: string;
  category: string;
  date: string;
  readTime: number;
  title: string;
  desc: string;
}

export const posts: BlogPost[] = [
  { slug: 'convert-figma-design-to-website', category: 'Services', date: 'Mar 9, 2026', readTime: 11, title: 'How to Convert a Figma Design to a Live Website (The Right Way)', desc: 'A practical guide to turning your Figma file into a real, working website. Covers automated tools vs hiring a developer, the build process, pricing, and what to look for in a Figma to code developer.' },
  { slug: 'wordpress-to-nextjs-migration', category: 'Services', date: 'Mar 9, 2026', readTime: 12, title: 'WordPress to Next.js Migration: Is It Worth It in 2026?', desc: 'An honest look at migrating from WordPress to Next.js. Real before-and-after numbers on speed, security, and cost. Covers the migration process, when it makes sense, and when to stay on WordPress.' },
  { slug: 'how-to-hire-web-developer', category: 'Services', date: 'Mar 9, 2026', readTime: 10, title: "How to Hire a Web Developer Without Getting Burned (A Developer's Honest Guide)", desc: 'What to look for, what to avoid, and how much to pay when hiring a web developer. Written by a developer who has seen every mistake clients make.' },
  { slug: 'signs-your-website-needs-redesign', category: 'Services', date: 'Mar 9, 2026', readTime: 9, title: '6 Signs Your Website Is Losing You Customers (And How to Fix It)', desc: 'Your website might be quietly sending visitors to your competitors. Here are the warning signs that your site needs a redesign and what a modern rebuild actually involves.' },
  { slug: 'saas-landing-page-design-tips', category: 'Services', date: 'Mar 9, 2026', readTime: 11, title: 'SaaS Landing Page Design: What Actually Converts in 2026', desc: 'What makes a SaaS landing page convert and what kills it. Covers headlines, social proof, CTAs, product demos, pricing, and the tech stack that affects your conversion rate.' },
  { slug: 'how-to-calculate-gpa', category: 'Education', date: 'Mar 8, 2026', readTime: 12, title: 'How to Calculate GPA: Complete Guide for High School and College', desc: 'Step-by-step guide to calculating unweighted and weighted GPA. Covers the 4.0 scale, AP and Honors bonuses, semester vs cumulative GPA, and strategies to raise your GPA.' },
  { slug: 'how-to-calculate-calorie-deficit', category: 'Health', date: 'Mar 7, 2026', readTime: 13, title: 'How to Calculate a Calorie Deficit for Weight Loss (The Simple Guide)', desc: 'Learn exactly how to calculate your calorie deficit for fat loss using TDEE and BMR. Includes the Mifflin-St Jeor formula, activity multipliers, protein targets, and why deficits shrink over time.' },
  { slug: 'north-node-by-sign', category: 'Astrology', date: 'Mar 6, 2026', readTime: 15, title: "North Node by Sign: What Your Nodal Axis Reveals About Your Soul's Purpose", desc: 'Detailed interpretations for all 12 North Node signs. Learn what your North Node means for your life purpose, what South Node patterns to release, and how to work with your nodal axis for genuine growth.' },
  { slug: 'how-to-find-asymptotes', category: 'Math', date: 'Mar 5, 2026', readTime: 11, title: 'How to Find Asymptotes Step by Step: Complete Guide with Examples', desc: 'Master vertical, horizontal, and oblique asymptotes. Covers the degree rule, long division for slant asymptotes, holes vs asymptotes, and worked examples for rational, exponential, and trig functions.' },
  { slug: 'normal-distribution-examples-real-life', category: 'Math', date: 'Mar 4, 2026', readTime: 13, title: 'Normal Distribution in Real Life: 10 Examples Explained Simply', desc: 'Understand the bell curve through real-world examples including heights, IQ scores, SAT results, manufacturing tolerances, and stock returns. Z-scores, the empirical rule, and how to calculate probabilities.' },
  { slug: 'css-units-explained-px-rem-em-vw-vh', category: 'CSS', date: 'Feb 18, 2026', readTime: 12, title: 'CSS Units Explained: PX vs REM vs EM vs VW vs VH in 2026', desc: 'A complete guide to CSS units. Learn when to use pixels, rem, em, vw, and vh with practical examples and conversion tips for responsive web design.' },
  { slug: 'how-much-does-a-website-cost', category: 'Business', date: 'Feb 17, 2026', readTime: 15, title: 'How Much Does a Website Cost in 2026? Complete Pricing Breakdown', desc: 'Transparent website development pricing for 2026. From $295 landing pages to $10,000+ enterprise apps. Real cost data from 50+ projects with interactive calculator.' },
  { slug: 'px-to-rem-conversion-guide', category: 'CSS', date: 'Feb 16, 2026', readTime: 10, title: 'PX to REM Conversion: Why You Should Stop Using Pixels in CSS', desc: 'Learn why rem units are better than pixels for accessible, responsive web design. Includes conversion formula, examples, and a free PX to REM converter tool.' },
  { slug: 'website-roi-how-to-calculate', category: 'Business', date: 'Feb 15, 2026', readTime: 11, title: "Website ROI: How to Calculate Your Website's Return on Investment", desc: 'Learn how to measure if your website investment is paying off. ROI formulas, real examples, industry benchmarks, and a free calculator to estimate your returns.' },
  { slug: 'hex-to-rgb-conversion-explained', category: 'Design', date: 'Feb 14, 2026', readTime: 9, title: 'HEX to RGB Conversion Explained with Examples and Formulas', desc: 'Understand how HEX color codes translate to RGB values. Learn the conversion formula, see practical examples, and use our free converter tool.' },
  { slug: 'css-to-tailwind-migration-guide', category: 'CSS', date: 'Feb 13, 2026', readTime: 14, title: 'CSS to Tailwind Migration: A Complete Step-by-Step Guide', desc: 'Migrate your CSS codebase to Tailwind CSS with this practical guide. Covers class mapping, responsive design conversion, and a free automated converter tool.' },
  { slug: 'linux-file-permissions-chmod-guide', category: 'Developer', date: 'Feb 12, 2026', readTime: 11, title: 'Linux File Permissions Explained: The Visual Chmod Guide', desc: 'Master Linux file permissions with this visual guide. Learn chmod notation, permission types, common permission sets, and use our interactive calculator.' },
  { slug: 'free-developer-tools-2026', category: 'Tools', date: 'Feb 11, 2026', readTime: 13, title: '26 Free Developer Tools for Web Designers and Developers in 2026', desc: 'A curated collection of 26 free online tools for frontend developers and web designers. CSS converters, color tools, calculators, and code utilities.' },
  { slug: 'color-codes-hex-rgb-hsl-explained', category: 'Design', date: 'Feb 10, 2026', readTime: 10, title: 'Understanding Color Codes: HEX, RGB, and HSL for Beginners', desc: 'A beginner-friendly guide to web color formats. Learn how HEX, RGB, and HSL work, when to use each one, and how to convert between them easily.' },
  { slug: 'yaml-vs-json-comparison-guide', category: 'Developer', date: 'Feb 9, 2026', readTime: 10, title: 'YAML vs JSON: Differences, Use Cases, and Conversion Guide', desc: 'Compare YAML and JSON formats side by side. Learn syntax differences, when to use which, and how to convert between them for Docker, Kubernetes, and configs.' },
  { slug: 'website-traffic-estimation-guide', category: 'Business', date: 'Feb 8, 2026', readTime: 11, title: "Website Traffic Estimation: How to Predict Your Site's Visitors", desc: 'Learn how to estimate website traffic before investing in SEO or paid ads. Covers SEO traffic formulas, PPC budgeting, and a free traffic calculator tool.' },
  { slug: 'what-is-rem-in-css', category: 'CSS', date: 'Feb 7, 2026', readTime: 8, title: 'What is REM in CSS? A Practical Guide with Examples', desc: 'Understand the rem unit in CSS and why it matters for responsive, accessible web design. Practical examples, browser support, and conversion tips included.' },
  { slug: 'css-to-scss-conversion-guide', category: 'CSS', date: 'Feb 6, 2026', readTime: 10, title: 'CSS to SCSS Conversion: Modernize Your Stylesheets in 2026', desc: 'Learn how to convert plain CSS to SCSS (Sass). Covers nesting, variables, mixins, and partials with practical before/after examples and a free converter tool.' },
  { slug: 'csv-to-sql-conversion-guide', category: 'Developer', date: 'Feb 5, 2026', readTime: 9, title: 'How to Convert CSV Data to SQL INSERT Statements', desc: 'Step-by-step guide to converting CSV files into SQL INSERT statements. Covers data types, escaping, bulk inserts, and a free automated converter tool.' },
  { slug: 'number-base-conversion-guide', category: 'Developer', date: 'Feb 4, 2026', readTime: 10, title: 'Number Base Conversion: Binary, Octal, Decimal, and Hexadecimal', desc: 'Master number system conversions with clear explanations and examples. Learn to convert between binary, octal, decimal, and hexadecimal with ease.' },
  { slug: 'website-development-pricing-guide-small-business', category: 'Business', date: 'Feb 3, 2026', readTime: 12, title: 'Website Development Pricing Guide for Small Businesses in 2026', desc: 'A no-nonsense pricing guide for small business owners. Learn what web development actually costs, what affects the price, and how to budget wisely.' },
  { slug: 'bandwidth-calculator-guide', category: 'Developer', date: 'Feb 2, 2026', readTime: 9, title: 'Bandwidth Calculator: Understanding Mbps, Gbps, and Transfer Speeds', desc: 'Demystify internet bandwidth units. Learn the difference between Mbps and MBps, calculate file transfer times, and estimate bandwidth needs for your projects.' },
  { slug: 'cgpa-to-percentage-conversion', category: 'Education', date: 'Feb 1, 2026', readTime: 7, title: 'CGPA to Percentage Conversion: Formula, Calculator, and Grade Guide', desc: 'Convert CGPA to percentage using the standard formula. Includes grade classification tables, university-specific multipliers, and a free calculator tool.' },
  { slug: 'px-to-cm-conversion-screen-print', category: 'Design', date: 'Jan 31, 2026', readTime: 8, title: 'PX to CM Converter: Screen Pixels to Print Measurements Explained', desc: 'Learn how to accurately convert pixels to centimeters for print design. Covers DPI, screen resolution, and provides a free converter with adjustable settings.' },
  { slug: 'celsius-to-fahrenheit-conversion', category: 'Education', date: 'Jan 30, 2026', readTime: 7, title: 'Celsius to Fahrenheit: Easy Conversion Formula and Quick Reference', desc: 'Convert Celsius to Fahrenheit instantly with the simple formula. Includes a reference table, common temperatures, cooking conversions, and a free calculator.' },
  { slug: 'em-vs-rem-css-which-to-use', category: 'CSS', date: 'Jan 29, 2026', readTime: 9, title: 'EM vs REM in CSS: Which One Should You Use and When?', desc: 'Understand the real difference between em and rem units in CSS. Learn when each one makes sense with practical examples and common patterns.' },
  { slug: 'best-free-css-unit-converters', category: 'Tools', date: 'Jan 28, 2026', readTime: 8, title: "Best Free CSS Unit Converters in 2026: A Developer's Guide", desc: 'A roundup of the best free CSS unit conversion tools available online. Compare PX to REM, EM, VW, VH, and percentage converters for web development.' },
  { slug: 'string-case-conventions-guide', category: 'Developer', date: 'Jan 27, 2026', readTime: 8, title: 'String Case Conventions: camelCase, snake_case, kebab-case Explained', desc: 'Learn all common string case conventions used in programming. When to use camelCase, snake_case, PascalCase, kebab-case, and more with language-specific guidelines.' },
  { slug: 'responsive-web-design-complete-guide', category: 'CSS', date: 'Jan 26, 2026', readTime: 15, title: 'Responsive Web Design: The Complete Guide for 2026', desc: 'Everything you need to know about responsive web design. Media queries, fluid grids, responsive images, mobile-first approach, and modern CSS techniques.' },
  { slug: 'nextjs-vs-react-which-to-choose', category: 'Developer', date: 'Jan 25, 2026', readTime: 12, title: 'Next.js vs React: Which One Should You Choose in 2026?', desc: 'An honest comparison of Next.js and React for web development. Covers performance, SEO, routing, deployment, and when each framework makes the most sense.' },
  { slug: 'web-development-cost-by-country', category: 'Business', date: 'Jan 24, 2026', readTime: 14, title: 'Web Development Cost by Country: A Global Pricing Comparison', desc: 'Compare web development rates across 30+ countries. Hourly rates, project costs, and quality expectations for hiring developers from different regions.' },
  { slug: 'hsl-color-model-explained', category: 'Design', date: 'Jan 23, 2026', readTime: 9, title: 'HSL Color Model Explained: Why Designers Prefer It Over RGB', desc: 'Learn why HSL is more intuitive than RGB for color selection. Understand hue, saturation, lightness, and how to create harmonious color palettes with HSL.' },
  { slug: 'vw-vh-units-responsive-layouts', category: 'CSS', date: 'Jan 22, 2026', readTime: 9, title: 'VW and VH Units in CSS: Creating Truly Responsive Layouts', desc: 'Master viewport units in CSS. Learn how vw and vh work, common use cases, pitfalls to avoid, and practical responsive design patterns with examples.' },
  { slug: 'tailwind-css-vs-regular-css', category: 'CSS', date: 'Jan 21, 2026', readTime: 11, title: 'Tailwind CSS vs Regular CSS: Pros, Cons, and Migration Tips', desc: 'An honest comparison of Tailwind CSS and traditional CSS. Covers developer experience, performance, maintainability, and when to choose each approach.' },
  { slug: 'custom-website-vs-template', category: 'Business', date: 'Jan 20, 2026', readTime: 12, title: 'Custom Website vs Template: Which One is Right for Your Business?', desc: 'Compare custom-built websites with template solutions like WordPress, Wix, and Squarespace. Real cost analysis, pros and cons, and decision framework.' },
];

export const postsBySlug: Record<string, BlogPost> = {};
for (const post of posts) {
  postsBySlug[post.slug] = post;
}

export const categoryColors: Record<string, string> = {
  Services: 'bg-blue-500/15 text-blue-400 border-blue-500/20',
  Education: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/20',
  Health: 'bg-rose-500/15 text-rose-400 border-rose-500/20',
  Astrology: 'bg-purple-500/15 text-purple-400 border-purple-500/20',
  CSS: 'bg-sky-500/15 text-sky-400 border-sky-500/20',
  Developer: 'bg-amber-500/15 text-amber-400 border-amber-500/20',
  Design: 'bg-pink-500/15 text-pink-400 border-pink-500/20',
  Business: 'bg-orange-500/15 text-orange-400 border-orange-500/20',
  Tools: 'bg-teal-500/15 text-teal-400 border-teal-500/20',
  Math: 'bg-violet-500/15 text-violet-400 border-violet-500/20',
};
